### PR TITLE
Adding ndc oslo 2020

### PR DESCRIPTION
**Pull request by spier**
Hi @olbpetersson, great job on the presentation together with Jessica.

Can you double check that I got this entry right? 
Not sure if the slides are also published somewhere, or if that would be worthwhile doing?

### CODE REVIEW

**Review by olbpetersson — APPROVED** [review]
Added slides and LGTM :)

**Comment by spier** [comment]
@olbpetersson is the deck https://speakerdeck.com/olbpetersson/ndc-oslo-devops-in-real-life-a-how-to public? I cannot access it.

**Comment by olbpetersson** [comment]
@spier I had apparantly left it in draft :/ it's published now and I could access it from an incognito tab so I think it should work now

**Comment by spier** [comment]
Yep, it is all working now. Thanks @olbpetersson !

**Pull request merged**
